import "../styles/tailwind.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="bg-white py-24">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">{children}</div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
